config/routes.rb
Rails.application.routes.draw do
  root "doctors#index"

  devise_for :doctors
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :doctors, only: [:index, :show] do
    get 'appointments', on: :member
    patch 'update_recommendation', on: :member
  end

  resources :users, only: [:profile] do
    get 'appointments', to: 'users#profile', as: 'appointments', on: :member
  end

  resources :categories, only: [:index, :show]
  resources :appointments, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    elsif user.doctor?
      can :manage, Appointment, doctor_id: user.id
      can :read, User
      can :create, Recommendation
    elsif user.patient?
      can :create, Appointment
      can :read, Doctor
      can :read, Recommendation, appointment: { user_id: user.id }
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor, dependent: :destroy
  belongs_to :user, dependent: :destroy

  scope :opened, -> { where(recommendation: [nil, ""]) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctors, dependent: :destroy
  validates :name, uniqueness: true

  scope :ordered, -> { order(:name) }
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  MAX_APPOINTMENT_COUNT = 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  belongs_to :category
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
  validates :phone, format: { with: /\A\d{10}\z/, message: "should be a 10-digit number" }

  scope :ordered, -> { order(:first_name) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments, dependent: :destroy
  validates :phone, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user_or_doctor!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def authenticate_user_or_doctor!
    if doctor_signed_in?
      authenticate_doctor!
    else
      authenticate_user!
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @doctors = Doctor.all
  end

  def create
    doctor = Doctor.find(appointment_params[:doctor_id])
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      flash[:success] = 'An appointment with the doctor was made successfully'
      redirect_to new_user_session_path
    else
      render :new
    end
  end

  private

  def appointment_params
    params.permit(:doctor_id, :user_id, :recommendation, :appointment_time)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = collection
  end

  def show
    @category = resource
  end

  private

  def collection
    Category.ordered
  end

  def resource
    collection.find(params[:id])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = collection
  end

  def show
    @doctor = resource
  end

  def update_recommendation
    @appointment = Appointment.find(params[:appointment_id])
    @appointment.update(recommendation: params[:recommendation])
    flash[:success] = 'Recommendation added successfully'
    redirect_to request.referer
  end

  def appointments
    @doctor = current_doctor # Assuming the doctor is logged in and stored in the current_user variable
    @appointments = @doctor.appointments.includes(:user)
  end

  private

  def collection
    Doctor.ordered
  end

  def resource
    collection.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @patient = current_user
    @appointments = @patient.appointments.includes(:doctor)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def appointment_time_options(doctor_id)
    selected_appointment_times = doctor_selected_appointment_times(doctor_id)
    all_appointment_times = ['8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00']

    available_appointment_times = all_appointment_times - selected_appointment_times
    options_for_select(available_appointment_times)
  end

  def update_appointment_times(doctor_id, appointment_time)
    doctor = Doctor.find(doctor_id)
    doctor.appointments.create(appointment_time: appointment_time)

    selected_appointment_times = doctor_selected_appointment_times(doctor_id)
    selected_appointment_times << appointment_time
    doctor.update(appointment_times: selected_appointment_times.uniq)
  end

  def appointment_already_exists?(doctor_id, appointment_time)
    selected_appointment_times = doctor_selected_appointment_times(doctor_id)
    selected_appointment_times.include?(appointment_time)
  end

  private

  def doctor_selected_appointment_times(doctor_id)
    doctor = Doctor.find(doctor_id)
    appointments = doctor.appointments.where.not(appointment_time: nil)
    selected_appointment_times = appointments.pluck(:appointment_time)
    current_appointment_time = appointments.find_by(user_id: current_user.id)&.appointment_time

    selected_appointment_times -= [current_appointment_time] if current_appointment_time.present?

    selected_appointment_times
  end

end

app/views/categories/index.html.erb
<div class="container" style="width: 300px;",>
  <ol class="list-group list-group-numbered text-center">
    <% @categories.each do |category| %>
      <%= link_to category, class: "text-decoration-none" do %>
        <li class="list-group-item">+<%= category.name%>+</li>
      <% end %>
    <% end %>
  </ol>
</div>

app/views/categories/show.html.erb
<div class="max-w-5xl mx-auto text-center">
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>
  <% @category.doctors.each do |doctor| %>
    <div class="flex justify-center">
      <div class="flex flex-col md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg">
        <%= image_tag doctor.category.name %>
        <h4><%= doctor.category.name %></h4>
        <p><%= doctor.first_name %> <%= doctor.last_name %></p>
        <% if doctor.appointments.opened.count >= Doctor::MAX_APPOINTMENT_COUNT %>
          <%= button_to 'Немає місць', '#', disabled: true, class: 'disabled-button' %> <br>
        <% else %>
        <% if doctor_signed_in? %>
          <button>Appointment not available</button>
        <% end %>
        <% unless doctor_signed_in? %>
          <%= form_tag appointments_path, method: :post do %>
            <%= hidden_field_tag :doctor_id, doctor.id %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <%= label_tag :appointment_time, 'Appointment Time:' %>
            <% if appointment_already_exists?(doctor.id, params[:appointment_time]) %>
              <p>Appointment time is not available.</p>
            <% else %>
              <%= select_tag :appointment_time, appointment_time_options(doctor.id) %>
              <%= submit_tag 'Make an appointment', class: "btn btn-success" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/doctors/appointments.html.erb
<div class="container" style="width: 500px;">
  <ol class="list-group list-group-numbered text-center">
    <% @appointments.each do |appointment| %>
      <li class="list-group-item">
        Patient:
        <%= appointment.user.first_name %> <%= appointment.user.last_name %> <br>
        <%= appointment.recommendation %>
        <% if appointment.recommendation.blank? %>
          <%= form_with(url: update_recommendation_doctor_path(current_doctor), method: :patch) do |f| %>
            <%= f.hidden_field :appointment_id, value: appointment.id %>
            <%= f.label :recommendation %>:
            <%= f.text_area :recommendation, rows: 6, cols: 40 %>
            <%= f.submit "Add Recommendation", class: "btn btn-primary" %>
          <% end %>
          Date&Time: <%= appointment.appointment_time %>
        <% end %> <br>
      </li>
    <% end %>
    <% if flash[:success] %>
      <div class="alert alert-success">
        <%= flash[:success] %>
      </div>
    <% end %>
  </ol>
</div>

app/views/doctors/index.html.erb
<div class="max-w-5xl mx-auto text-center">
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>
  <% @doctors.each do |doctor| %>
    <div class="flex justify-center">
      <div class="flex flex-col md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg">
        <%= image_tag doctor.category.name %>
        <div class="p-6 flex flex-col justify-start">
          <h5><%= doctor.category.name %></h5>
          <p><%= doctor.first_name %> <%= doctor.last_name %></p>
          <% if doctor.appointments.opened.count >= Doctor::MAX_APPOINTMENT_COUNT %>
            <%= button_to 'Busy schedule', '#', disabled: true, class: 'disabled-button' %> <br>
          <% else %>
          <% if doctor_signed_in? %>
            <button class="btn btn-secondary">Appointment not available</button>
          <% end %>
            <% unless doctor_signed_in? %>
              <%= form_tag appointments_path, method: :post do %>
                <%= hidden_field_tag :doctor_id, doctor.id %>
                <%= hidden_field_tag :user_id, current_user.id %>
                <%= label_tag :appointment_time, 'Appointment Time:' %>
                <%= select_tag :appointment_time, appointment_time_options(doctor.id) %>
                <%= submit_tag 'Make an appointment', class: "btn btn-success" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container bg-white opacity-75">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      <li class="nav-item"><p class="nav-link px-2 text-muted">© <%= Date.today.year %> Clinic™ All Rights Reserved.</p></li>
    </ul>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64"><path fill="currentColor" d="M56.609 1.114s-48.788-.015-48.774 0C3.338 1.114.81 3.439.81 8.188v48.966c0 4.443 2.273 6.769 6.766 6.769h49.173c4.493 0 6.769-2.21 6.769-6.769V8.188c.001-4.634-2.275-7.074-6.909-7.074zm-8.343 52.518h-8.302v-17.82H24.469v17.82h-8.301V13.896h8.301v15.053h15.495V13.896h8.302v39.736z"/></svg>
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <% if doctor_signed_in? %>
          <li><h3><%= link_to "Appointments", appointments_doctor_path(current_doctor.id), class: "text-white text-decoration-none" %></h3></li>
        <% else %>
          <li><h3><%= link_to "Doctors|", doctors_path, class: "text-white text-decoration-none" %></h3></li>
          <li><h3><%= link_to "Categories", categories_path, class: "text-white text-decoration-none" %></h3></li>
          <% if user_signed_in? %>
            <li><h3><%= link_to "|Recommendations", appointments_user_path(id: current_user.id), class: "text-white text-decoration-none" %></h3></li>
          <% end %>
        <% end %>
      </ul>
      <div class="text-end">
        <% if doctor_signed_in? %>
          <p>Welcome, doctor <%= current_doctor.first_name %></p>
          <%= button_to "Exit", destroy_doctor_session_path, method: :delete, form: {turbolink: false}, class: "btn btn-outline-light me-2" %>
        <% elsif user_signed_in? %>
          <p>Welcome, pppatient <%= current_user.first_name %></p>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, form: {turbolink: false}, class: "btn btn-outline-light me-2" %>
        <% else %>
          <%= link_to new_user_registration_path do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="56" style="fill: red;" height="56" viewBox="0 0 24 24"><path fill="currentColor" d="M12 10c2.21 0 4-1.79 4-4s-1.79-4-4-4s-4 1.79-4 4s1.79 4 4 4m0-6c1.1 0 2 .9 2 2s-.9 2-2 2s-2-.9-2-2s.9-2 2-2m6.39 8.56C16.71 11.7 14.53 11 12 11s-4.71.7-6.39 1.56A2.97 2.97 0 0 0 4 15.22V22h2v-6.78c0-.38.2-.72.5-.88C7.71 13.73 9.63 13 12 13c.76 0 1.47.07 2.13.2l-1.55 3.3H9.75C8.23 16.5 7 17.73 7 19.25S8.23 22 9.75 22H18c1.1 0 2-.9 2-2v-4.78c0-1.12-.61-2.15-1.61-2.66M10.94 20H9.75c-.41 0-.75-.34-.75-.75s.34-.75.75-.75h1.89l-.7 1.5M18 20h-4.85l2.94-6.27c.54.2 1.01.41 1.41.61c.3.16.5.5.5.88V20Z"/></svg>
          <% end %>
          <%= link_to new_doctor_session_url do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" viewBox="0 0 26 26"><path fill="currentColor" d="M13 0c-2.1 0-3.357.32-4.156.719c-.4.2-.684.41-.875.625a2 2 0 0 0-.313.531a1 1 0 0 0-.062.25l-.532 6.844c-.007.042.007.11 0 .156L7 9.813A1.003 1.003 0 0 0 7 10c0 3.3 2.7 6 6 6s6-2.7 6-6v-.156a1.003 1.003 0 0 0 0-.031l-.594-7.688a1 1 0 0 0-.062-.25s-.121-.316-.313-.531c-.191-.216-.475-.426-.875-.625C16.357.319 15.1 0 13 0zm0 16c-6.6 0-12 3.106-12 5.906V26h24v-4.094c0-2.66-4.882-5.59-11.031-5.875A14.294 14.294 0 0 0 13 16zm0-14c1.9 0 2.849.3 3.25.5c.134.067.15.093.188.125l.406 5.125C15.924 7.806 14.67 8 13 8s-2.923-.194-3.844-.25l.406-5.125c.037-.032.054-.058.188-.125c.401-.2 1.35-.5 3.25-.5zm-.813 1v1.188H11v1.625h1.188V7h1.624V5.812H15V4.188h-1.188V3h-1.624zM10 18.25L12.563 24H3v-2.094c0-.745 2.55-2.927 7-3.656zm6 0c4.45.73 7 2.911 7 3.656V24h-9.563L16 18.25z"/></svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codica</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'favicon.ico'%>
  </head>

  <body class="bg-image">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/profile.html.erb
<div class="container" style="width: 500px;">
  <ol class="list-group list-group-numbered text-center">
    <% @appointments.each do |appointment| %>
      <li class="list-group-item">
        <%= appointment.doctor.category.name %> <%= appointment.doctor.first_name %> <%= appointment.doctor.last_name %> <br>
        <% if appointment.recommendation.present? %>
          Recommendation: <%= appointment.recommendation %>
        <% else %>
          <p>Not yet..</p>
          Date&Time: <%= appointment.appointment_time %>
        <% end %>
      </li>
    <% end %>
  </ol>
</div>